version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "No build step required for static site"
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://my-static-website-pipeline --delete

artifacts:
  files:
    - '**/*'
